### ISSUE TITLE
May I find a Bug in this project.

### ISSUE THREAD

**Issue by AI0day** [blasty/ropstone#2]
when I download this project,and run this script,get following infomation:
Traceback (most recent call last):
  File "ropstone.py", line 36, in <module>
    class ropstone():
  File "ropstone.py", line 52, in ropstone
    "ks_const" : KS_ARCH_ARM,
NameError: name 'KS_ARCH_ARM' is not defined

So,I suggest you to check your code ;-)

**Comment by Schtrudel** [comment]
May I suggest you use the latest version of Keystone (http://www.keystone-engine.org/download/), and not just trying 'pip install keystone'? 
pip installs version 0.2.1, while the actual working version is 0.9.1.

**Comment by AI0day** [comment]
I will try it，thx ；-）
